### ISSUE TITLE
Add QT_PLUGIN_PATH to AppRun file

### ISSUE THREAD

**Issue by absolutelynothinghere** [sudo-give-me-coffee/make-portable#2]
First I want to say major thanks for this tool, it's perfect for novices like me who want to quickly create AppImages. 🙏

Second I would like to suggest that this line gets added to generated AppRun files:

```bash
export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt5/plugins
```

This seems to be an easy fix for Qt5 applications to work, as otherwise they throw an error about missing plugins and refuse to start. One example is [mGBA](https://mgba.io/) which I just packaged today using this fix.

Cheers.

**Comment by sudo-give-me-coffee** [comment]
Sorry for the delay in answer, but i added this on commit https://github.com/sudo-give-me-coffee/make-portable/commit/291b0dc24b1528fb7d38dd749c742315cd483115
