### ISSUE TITLE
Wrapped .so file produces "invalid ELF header" error

### ISSUE THREAD

**Issue by absolutelynothinghere** [sudo-give-me-coffee/make-portable#3]
Hello again 😄 today I updated make-portable for the first time in months to try out the new "wrapping" system, but I ran into a problem... Since some libraries (.so) get wrapped, they cannot be read properly by the portable program. For example, running an AppImage with a wrapped `libpulsecommon-15.0.so` produces the error "invalid ELF header" and prevents the AppImage from starting, while the unwrapped version runs fine and doesn't produce any errors.

Perhaps it's better to wrap files on a whitelist basis? As in letting the user decide whether to wrap all files, certain defined files, or only executables (in /bin, /usr/bin...etc).

Also while I'm here, I have some questions regarding the wrapping system; is it okay to ask them on this issue? Or is there a better place for questions? Thank you.

**Comment by sudo-give-me-coffee** [comment]
> Perhaps it's better to wrap files on a whitelist basis?

The scripts has a blocklist, initialy only with video drivers, [belllow this line](https://github.com/sudo-give-me-coffee/make-portable/blob/4ad2a01c1603366b52e1b862c8d839f2fdc116d5/make-portable.sh#L200) i will put the problematic libs

> Also while I'm here, I have some questions regarding the wrapping system; is it okay to ask them on this issue? Or is there a better place for questions?

Please open a new issue is more easy to organize if project grows up
